### ISSUE TITLE
Add support for multiple input of openapi files?

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-plugin-codegen-openapi#76]
We have most of our APIs defined in many different files. Could you add support for having multiple openapi files passed in the same time and having all of them merged in the IR ?

**Comment by austinvalle** [comment]
Hey @remyleone 👋🏻 , couple questions to help frame my understanding:

- Are the multiple files all fragments of an OpenAPI spec that need to be combined to be valid, or are they all valid OpenAPI specs individually?
- If combined, would you expect all other configuration options (generator config, arguments, etc.) to work the same regardless of the amount of files.
   - So not multiple IR files as output, for example

If you have an example of your multiple OpenAPI specs that you can share that would also be helpful!

**Comment by remyleone** [comment]
They are all valid OpenAPI specs individually. https://www.scaleway.com/en/developers/static/scaleway.instance.v1.Api.yml for instance. We have an open api definition like that for all our products at Scaleway.
You can find all the different APIs definition there: https://www.scaleway.com/en/developers/api/

At the moment I'm not sure about whether we should generate each openapi file individually or whether we should pass all the different definition in one go. I guess that having the possibility to pass them all in one go could open the door to having cross reference between different products/APIs.
As for the generator config I was thinking of having a config for each products but I could be convinced to put everything in a single file for a good reason (if it was require to make cross reference work for instance).

**Comment by austinvalle** [comment]
Thanks for that context!

> _As for the generator config I was thinking of having a config for each products_

I think this aligns with our initial thoughts for code generation, you could have say, multiple IR JSON outputs that are used to generate one Terraform provider. So for example:
- `instance.v1.generator_config.yml` + Instance v1 OpenAPI spec -> `instance.v1.ir.json` -> instance resources/data sources in the `scaleway` provider
- `account.v2.generator_config.yml` +  Account v2 OpenAPI spec -> `account.v2.ir.json` -> account resources/data sources in the `scaleway` provider

I can see similar possibilities for say, the kubernetes OpenAPI specs: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/v3, which would eventually be rolled into one Terraform provider.

**Comment by austinvalle** [comment]
Currently, we're leaning towards focusing on a single run of the `tfplugingen-openapi generate` command comprising of:
- 1 OpenAPI spec as the entry point
- 1 Generator config that describes what needs to be parsed from the OpenAPI spec

So if multiple OpenAPI specs exist that are **not connected**, we'd view those as separate runs of the `tfplugingen-openapi generate` command, where each would have it's own generator config.

I do believe there is an opportunity to support OpenAPI specs that are **connected** via a remote/URL reference with `$ref`, as that is clearly defined by JSON references. An OpenAPI spec that would fit into this support would be something like the [Digital Ocean OpenAPI specs](https://github.com/digitalocean/openapi/tree/main/specification/resources) which makes remote references to separate OpenAPI spec files but still only has [one entry point](https://github.com/digitalocean/openapi/blob/main/specification/DigitalOcean-public.v2.yaml).

I've created a new issue, #89, to track the interest in this support, so if this sounds like something that fits what you're looking for, please consider giving it a 👍🏻
