### ISSUE TITLE
Enhance functionality related to overriding or defining new properties for an attribute

### ISSUE THREAD

**Issue by AgustinBettati** [hashicorp/terraform-plugin-codegen-openapi#84]
**Context and use case**

Currently the generator config allows overriding of attributes, but limits its functionality to modifying the description property:
```
schema:
      attributes:
        overrides:
          labels:
            description: other description
```

I have been trying this tool with the intention of replacing existing manual schema and type definitions with autogenerated ones using an existing API spec. In order to reach this parity there are several properties that are missing in the resulting provider code specification generated from the API spec, which is reasonable as the API spec lacks terraform-specific information.

**Enhancement request**

Here is a list of use cases I found would be useful for defining within the generator config:

- Define **plan modifiers** for specific attributes. This is useful for common plan modifiers such as `RequiresReplace` and `UseStateForUnkown`.
- Define **validators** for specific attributes. Apart from validators that are generated from API Spec properties, there are other validations such as `ConflictsWith` which cannot be represented easily in an OpenAPI Spec.
- Allow overriding the resulting **name** of an attribute, giving flexibility in the case that terraform schema has a different name from the definition in the API.
- Marking an attribute as **sensitive**. This is information that likely cannot be inferred from the API Spec but highly relevant for terraform schema.
- Allow override of the `computed_optional_required` property for an attribute. While the tool has a certain logic to define this value for attributes, it would be helpful to give flexibility to the user to cover specific edge cases.

**Comment by austinvalle** [comment]
Combining this request with #86 as they are closely related 👍🏻
