### ISSUE TITLE
Allow configurable options for array properties with nested objects

### ISSUE THREAD

**Issue by AgustinBettati** [hashicorp/terraform-plugin-codegen-openapi#85]
**Context**
I have been trying this tool with the intention of replacing existing manual schema and type definitions with autogenerated ones using an existing API spec. In order to reach this parity there are differences in how array types are being generated in the provider spec code compared to my actual terraform schemas.

**Enhancement request**
Currently schemas of `"type" : "array"` with nested objects are being defined as attribute lists. While this is correct, terraform has a broader set of possibilities:
- can be of type `list_nested` or `set_nested`.
- defined as an `attribute` or as a `block`.

Providing this terraform specific information in the generator config, potentially in `attributes` property, would give users more flexibility in the generated provider code spec.

**Comment by austinvalle** [comment]
Combining this request with #86 as they are closely related 👍🏻
